import fs from 'node:fs';

const rawMissing = JSON.parse(fs.readFileSync('docs/review-i18n-missing.json', 'utf8'));

const en = {
  "(Дневник намерений по Дёрнеру)": "(Dörner Intentions Journal)",
  "(Не вызвала ли попытка решить одну проблему кризис в соседней сфере?).": "(Did attempting to solve one problem spark a crisis in an adjacent domain?).",
  "(Не действовать «баллистически» — всегда формулировать ожидание).": "(Avoid ballistic action — always articulate explicit expectations).",
  "(Сверить факт с прогнозом и отчетом подразделения).": "(Cross-check actual outcomes against forecasts and department reports).",
  ". Ставка в умеренном диапазоне.": ". Tax rate in moderate range.",
  ": бросить все средства на одну сиюминутную жалобу, пробив дыру в бюджете.": ": dumping all funds into a single immediate complaint, tearing a hole in the budget.",
  ": начать несколько строек подряд, не дождавшись окончания {n0}-месячного срока первой.": ": launching several construction projects in a row without waiting through the {n0}-month delay of the first.",
  ": покрывать дефицит займами, пока проценты не сожрут весь бюджет.": ": covering deficits with loans until interest payments swallow the whole budget.",
  ": тратить деньги на рекламу туризма, когда в городе нет свободных гостиничных мест.": ": spending money on tourism promotion when the town has zero vacant hotel beds.",
  "{n0} из {n1} целей выполнено ({n2}%)": "{n0} of {n1} goals met ({n2}%)",
  "{n0} мес. · Высокая": "{n0} mo. · High",
  "{n0} мес. · Средняя": "{n0} mo. · Medium",
  "{n0} мес. · Стандартная": "{n0} mo. · Standard",
  "{n0} мес. · Экстремальная": "{n0} mo. · Extreme",
  "«Долговая петля»": "“Debt Loop”",
  "«Жилищный вопрос спокоен: вместимость фонда {n0} мест, свободно {n1} квартир. Дефицита нет».": "“Housing conditions are calm: total capacity is {n0} beds with {n1} vacant units. No shortage.”",
  "«Нетерпеливое перерегулирование»": "“Impatient Overcorrection”",
  "«Рекламный мираж»": "“Advertising Mirage”",
  "«Синдром ремонтника»": "“Repairman Syndrome”",
  "«Социальный климат благоприятный: благополучие {n0}/{n1}. Рабочие довольны условиями ({n2}), семьи чувствуют заботу ({n3}), пожилые спокойны ({n4})».": "“Social climate is favorable: wellbeing at {n0}/{n1}. Workers are satisfied ({n2}), families feel supported ({n3}), seniors are secure ({n4}).”",
  "«Туристический сектор работает в спокойном режиме: вместимость {n0} мест, принято {n1} гостей. Спрос составляет {n2} чел.».": "“Tourism sector operates smoothly: capacity {n0} beds, hosted {n1} guests. Visitor demand is {n2} visitors.”",
  "«Фабрика работает стабильно. Станки требуют регулярного внимания, запасы на складе соответствуют обычному месячному обороту».": "“The watch factory operates steadily. Equipment requires steady maintenance; warehouse inventory matches standard monthly turnover.”",
  "«Финансовое положение устойчиво. Долг города: {n0} тыс. м., казна: {n1} тыс. м. Текущий баланс под контролем».": "“Financial standing is sound. City debt: {n0}k M., treasury: {n1}k M. Operational cashflow is under control.”",
  "· Сейчас:": "· Currently:",
  "· Финансы и миграция": "· Finances & Migration",
  "· каждый шаг оставляет след в системе города": "· every step leaves a footprint across the urban system",
  "Администрация развернула агрессивную рекламу туризма (бюджет {n0} тыс./мес.), однако гостиничных мест всего {n1}, а в городе возник дефицит жилья ({n2} мест при населении {n3}). Балансируйте развитие рекреации и базовые потребности горожан.": "The administration launched aggressive tourism advertising ({n0}k M/mo budget), but hotel capacity is only {n1} beds, while housing shortage reached {n2} beds with population {n3}. Balance recreation growth against residents' basic needs.",
  "Анатомия системных связей": "Anatomy of System Connections",
  "Баланс: {n0} тыс. м. · Долг: {n1} тыс.": "Balance: {n0}k M. · Debt: {n1}k",
  "Балансирующий": "Balancing",
  "Бутылочное горлышко туризма": "Tourism Bottleneck",
  "В «Решениях» настройте ползунки, прочитайте What-If подсказки о прямых эффектах и системных рисках.": "In “Decisions”, adjust sliders and examine What-If previews on direct effects and systemic risks.",
  "В кабинет бургомистра": "To Mayoral Cockpit",
  "В книге «Логика неудачи» участники терпели крах, пытаясь воздействовать на одну переменную и игнорируя замкнутые петли обратной связи.": "In “The Logic of Failure”, participants failed by manipulating a single variable while ignoring closed feedback loops.",
  "Ваш город · Ваши решения": "Your City · Your Decisions",
  "Ваш стиль управления Лоххаузеном отличается высокой системной дисциплиной. Вы избежали типичных психологических ловушек, описанных Дёрнером, и продемонстрировали способность мыслить контурами обратной связи.": "Your management style in Lohhausen shows high systemic discipline. You avoided typical psychological traps described by Dörner and demonstrated feedback-loop thinking.",
  "Вдумчивое системное управление:": "Thoughtful Systemic Management:",
  "Вопросы для саморефлексии:": "Self-Reflection Questions:",
  "Время идет только по кнопкам «Следующий месяц» и «{n0} месяца». Пока вы анализируете доклады советников или настраиваете политику, город ждет.": "Time only advances with “Next Month” and “+{n0} Months”. While you analyze reports or adjust policy, the city waits.",
  "Вы проявили терпение, учитывали временные лаги и контролировали последствия решений через доклады подразделений.": "You exercised patience, accounted for time delays, and monitored policy consequences through department reports.",
  "Выполнено: {n0} из {n1} ({n2}%)": "Completed: {n0} of {n1} ({n2}%)",
  "ГОРОДСКИЕ СЛУЖБЫ": "MUNICIPAL SERVICES",
  "Главные когнитивные ловушки Дёрнера": "Dörner's Primary Cognitive Traps",
  "Главы {n0}–{n1} «Логики неудачи»; немецкое издание Rowohlt, {n2}: с. {n3}–{n4}.": "Chapters {n0}–{n1} of “The Logic of Failure”; German edition Rowohlt, {n2}: pp. {n3}–{n4}.",
  "Горизонт — {n0} г. ({n1} мес.)": "Horizon — {n0} yrs ({n1} mo.)",
  "Город вошел в фазу нестабильности: налоги завышены до {n0}%, рабочие недовольны низкими зарплатами, а инфраструктура запущена. Проявите комплексное мышление, избегая синдрома ремонтника и нетерпеливого перерегулирования.": "The town entered a phase of instability: taxes inflated to {n0}%, workers disgruntled by low wages, and infrastructure neglected. Exercise holistic thinking without succumbing to repairman syndrome or impatient overcorrection.",
  "Групповой нелинейный расчет удовлетворенности (рабочие, семьи, пожилые).": "Group-specific non-linear wellbeing model (workers, families, seniors).",
  "Датированная отчетность и система советов подразделений.": "Dated reports and mayoral advisory council system.",
  "Датированные отчеты — отражение неполноты информации в эксперименте Дёрнера. Спрашивайте то, что нужно для проверки конкретной гипотезы.": "Dated reports reflect information incompleteness in Dörner's experiment. Request only what is required to test a concrete hypothesis.",
  "Действующая политика": "Active Policy",
  "Держите налоги в умеренном диапазоне ({n0}–{n1}%), чтобы не подавлять активность.": "Keep taxes in a moderate range ({n0}–{n1}%) to avoid suppressing economic activity.",
  "Для осмысленного опыта двигайтесь по одному месяцу: «Хроника хода» сразу объяснит, что и почему изменилось.": "For an insightful experience, advance month by month: “Turn Chronicle” explains what shifted and why.",
  "Добавляет {n0} гостиничных мест через {n1} месяцев. Создает физическую базу для приема гостей города и доходов казны.": "Adds {n0} tourist beds after {n1} months. Creates physical capacity to host guests and generate municipal revenue.",
  "Долговая спираль": "Debt Spiral",
  "Доходы бюджета": "Budget Revenues",
  "ЕЖЕМЕСЯЧНЫЕ СТАВКИ": "MONTHLY RATES",
  "Жилье и город": "Housing & Town",
  "Жильё": "Housing",
  "Запас жилья умеренный (~{n0} мест). С учетом {n1}-месячного строительного лага стоит готовить расширение заранее.": "Housing margin is modest (~{n0} beds). Given the {n1}-month construction delay, expansion should be planned ahead.",
  "ИЛЛЮСТРАТИВНЫЕ АРХЕТИПЫ ПО КНИГЕ ДЁРНЕРА": "ILLUSTRATIVE ARCHETYPES FROM DÖRNER'S BOOK",
  "ИТОГИ СЦЕНАРИЯ: Свободное управление (Песочница)": "SCENARIO RESULTS: Free Governance (Sandbox)",
  "Игрок (Вы)": "Player (You)",
  "Из книги Дёрнера": "From Dörner's Book",
  "Изучайте связи. Учитывайте время и задержки.": "Examine connections. Account for time and delays.",
  "Изучите доклады советников.": "Study advisory reports.",
  "Индекс благополучия жителей (%)": "Resident Wellbeing Index (%)",
  "Инженерные допущения": "Engineering Assumptions",
  "Кабинет бургомистра": "Mayoral Cockpit",
  "Кабинет советников": "Advisory Council",
  "Казна и налоги": "Treasury & Taxes",
  "Какие побочные эффекты проявились?": "What side effects emerged?",
  "Какое из принятых вами решений принесло максимальный отложенный эффект — позитивный или разрушительный?": "Which decision yielded the greatest delayed impact — positive or destructive?",
  "Какую главную цель вы преследовали в этой партии, и менялась ли она по ходу времени?": "What primary goal did you pursue, and did it evolve over time?",
  "Классический эксперимент Лоххаузена {n0} года": "Classic Lohhausen Experiment of {n0}",
  "Конрад (Системный мыслитель)": "Konrad (Systemic Thinker)",
  "ЛОХХАУЗЕН · СИМУЛЯТОР СИСТЕМНОГО МЫШЛЕНИЯ ПО ДЁРНЕРУ": "LOHHAUSEN · SYSTEM DYNAMICS SIMULATOR AFTER DÖRNER",
  "Лоххаузен ожидает первых решений. Ознакомьтесь с докладами подразделений и определите приоритеты.": "Lohhausen awaits initial decisions. Examine department reports and set strategic priorities.",
  "Лоххаузен превратился в самоподдерживающийся цветущий город с максимальным индексом благополучия ({n0}).": "Lohhausen transformed into a thriving self-sustaining town with peak wellbeing ({n0}).",
  "Маленький город: около {n0} жителей в немецких среднегорьях.": "Small town: approximately {n0} inhabitants in the German uplands.",
  "Мест: {n0} · Посетителей: {n1}": "Beds: {n0} · Visitors: {n1}",
  "Миграция": "Migration",
  "Муниципальная часовая фабрика — основа городской экономики.": "The municipal watch factory is the foundation of the town economy.",
  "На главном экране кабинета советники (Герр Краузе, Фрау Вебер, Герр Бауэр, Доктор Франк, Фрау Линдеманн) сообщают о текущих узких местах.": "On the mayoral cockpit, advisors (Herr Krause, Frau Weber, Herr Bauer, Dr. Frank, Frau Lindemann) report bottlenecks.",
  "Нажмите на район города, чтобы открыть отчет подразделения": "Click a city district to open the department report",
  "Накопление отложенных дефицитов, резкий износ инфраструктуры и финансовый кризис во второй половине срока.": "Accumulation of delayed deficits, severe infrastructure decay, and fiscal crisis in the second half of the term.",
  "Налоговая база": "Tax Base",
  "Налоговая петля оттока": "Tax Outflow Loop",
  "Например: увеличить ремонт станков до {n0} тыс.; через полгода проверить выпуск и прибыль фабрики.": "Example: increase maintenance to {n0}k; six months later verify watch output and factory profit.",
  "Начало": "Start",
  "Неполнота информации, обратные связи, временные задержки и конфликты целей.": "Incomplete information, feedback loops, time delays, and goal conflicts.",
  "Новая политика начнет действовать со следующего хода.": "New policy will take effect on the next turn.",
  "Обновить все службы": "Update All Services",
  "Обновить отчеты всех {n0} подразделений": "Update reports for all {n0} departments",
  "Оборудование градообразующего часового завода изношено до критических {n0}%. Накоплен краткосрочный долг в {n1} тыс. марок, а свободных средств в казне осталось всего {n2} тыс. Предотвратите остановку завода и верните рентабельность.": "Equipment at the town's key watch plant is worn down to a critical {n0}%. Short-term debt has reached {n1}k Marks, with only {n2}k left in the treasury. Prevent a factory shutdown and restore solvency.",
  "Оборудование изношено ({n0}%). Проект добавит {n1} пунктов оборудования (~{n2}%) и повысит производительность линии за {n3} месяцев.": "Equipment is degraded ({n0}%). Project adds {n1} equipment points (~{n2}%) and enhances line throughput over {n3} months.",
  "Один управленческий цикл": "One Governance Cycle",
  "Осталось месяцев: {n0}": "Months remaining: {n0}",
  "Отчет службы": "Department Report",
  "ПРИЧИННО-СЛЕДСТВЕННЫЙ АНАЛИЗ": "CAUSAL ANALYSIS",
  "Петля износа станков": "Equipment Wear Loop",
  "Петля привлекательности и задержки жилья": "Attractiveness & Housing Delay Loop",
  "Планомерное инвестирование из операционной прибыли, заблаговременное строительство жилья, удержание безработицы ниже {n0} человек.": "Consistent capital investment funded by operating profits, proactive housing construction, and unemployment below {n0} people.",
  "По книге Дитриха Дёрнера «Логика неудачи» (Die Logik des Mißlingens). Здесь можно исследовать описанные в книге системные связи.": "Based on Dietrich Dörner's book “The Logic of Failure” (Die Logik des Mißlingens). Explore systemic dynamics described in the text.",
  "Повышение налога кажется легким способом закрыть дыру в казне. Однако бремя снижает привлекательность Лоххаузена: жители начинают уезжать, число налогоплательщиков падает, и в итоге налоговые поступления снова снижаются, несмотря на высокую ставку.": "Raising taxes appears to be a quick fix for the treasury. But the burden degrades Lohhausen's appeal: residents emigrate, taxpayer base shrinks, and revenues plummet despite higher rates.",
  "Поддерживайте расходы на обучение для планомерного роста квалификации рабочих.": "Maintain education funding for continuous improvement of workforce skills.",
  "Положение в вашем Лоххаузене прямо сейчас:": "Current conditions in your Lohhausen right now:",
  "Посмотреть полный финансовый отчет": "View full financial report",
  "Привлекательность": "Attractiveness",
  "Применяется каждый шаг": "Applied every turn",
  "Принятие решений без последующей проверки эффектов; пренебрежение регулярными отчетами служб; позднее обнаружение скрытых кризисов.": "Taking actions without verifying outcomes; neglecting regular reports; belatedly noticing latent crises.",
  "Принять решения": "Commit Decisions",
  "Пробел": "Space",
  "Проверьте гипотезу.": "Verify your hypothesis.",
  "Проект оплачивается сразу и один раз": "Project is paid once upfront",
  "Производство": "Production",
  "Процентный долг города ({n0}% в месяц) и кассовый баланс.": "Municipal debt interest ({n0}% monthly) and cash balance.",
  "Пять критических переменных: финансы, производство, работа, жилье и благополучие.": "Five critical variables: finances, manufacturing, employment, housing, and wellbeing.",
  "Развитие туризма требует синхронного роста гостиниц, рекламы и доступных рабочих рук.": "Tourism development requires synchronous expansion of accommodations, marketing, and available labor.",
  "Располагаемый доход": "Disposable Income",
  "Реактивная ловушка": "Reactive Trap",
  "Решения и проекты": "Decisions & Projects",
  "СИСТЕМНЫЕ НАБЛЮДЕНИЯ ПО ВАШЕЙ ПАРТИИ": "SYSTEMIC OBSERVATIONS FROM YOUR SESSION",
  "СНАЧАЛА — ВОПРОСЫ И АНАЛИЗ": "FIRST — INQUIRY & ANALYSIS",
  "СЦЕНАРИЙ: Свободное управление (Песочница)": "SCENARIO: Free Governance (Sandbox)",
  "Свободно мест: {n0} из {n1}": "Vacant beds: {n0} of {n1}",
  "Сводка на главной показывает общее состояние. Подробный отчет раскрывает причины и скрытые механизмы.": "The cockpit overview shows high-level state. Detailed reports disclose root causes and underlying dynamics.",
  "Сделайте ход.": "Take a turn.",
  "Сейчас налоговая ставка составляет": "Current tax rate is",
  "Системный радар здоровья города": "Systemic Urban Health Radar",
  "Системный эталон": "Systemic Benchmark",
  "Скачать подробный аналитический отчет": "Download detailed analytical report",
  "Следите за балансом между объемом выпуска и внешним спросом на часы.": "Keep watch production balanced with external market demand.",
  "Службы": "Services",
  "Службы реагируют на реальные изменения в городе": "Services respond to real city developments",
  "Случалось ли так, что меры по спасению одной сферы неожиданно разрушали баланс в соседней?": "Did interventions aimed at rescuing one domain unexpectedly disrupt balance in another?",
  "Сопоставьте реальный факт с ожиданием. Если что-то пошло не так, исследуйте обратные связи в разделе «Анатомия связей».": "Compare actual outcomes with expectations. If unexpected shifts occur, inspect feedback loops in “Anatomy of Feedback”.",
  "Сравнение с модельными профилями поведения": "Comparison with Model Behavioral Profiles",
  "Сравнение с эталонами Дёрнера: Индекс благополучия жителей": "Comparison with Dörner Benchmarks: Resident Wellbeing Index",
  "Стандартная": "Standard",
  "Стандартные стартовые условия города Лоххаузен. Горизонт планирования — {n0} лет ({n1} месяцев). Ваша задача — развивать город, соблюдая баланс между экономикой фабрики, благополучием жителей и устойчивостью казны.": "Standard initial setup for Lohhausen. Planning horizon is {n0} years ({n1} months). Develop the town while balancing factory health, resident wellbeing, and treasury solvency.",
  "Станки: {n0}% · Выпуск: {n1} шт.": "Equipment: {n0}% · Output: {n1} pcs",
  "Стартовая диспозиция Лоххаузена": "Initial Disposition of Lohhausen",
  "Стратегия:": "Strategy:",
  "Строительство жилья: {n0} месяцев лага и {n1} новых мест.": "Housing construction: {n0} months delay and {n1} new residential places.",
  "Сформулируйте изменение.": "State your rationale.",
  "Текущая политика действует каждый месяц. Проекты оплачиваются один раз и дают результат после завершения срока строительства.": "Active policies apply monthly. Capital projects are funded once upfront and deliver outcomes when construction ends.",
  "Траектории Конрада (системный эталон) и Маркуса (реактивная ловушка) построены на основе описаний из глав {n0} и {n1} книги «Логика неудачи» как дидактические ориентиры для самоанализа.": "The trajectories of Konrad (systemic benchmark) and Marcus (reactive trap) are didactic models drawn from chapters {n0} and {n1} of “The Logic of Failure”.",
  "Требование: {n0} · Результат:": "Target: {n0} · Outcome:",
  "Три вопроса рефлексии Дёрнера": "Dörner's Three Questions of Reflection",
  "Туризм и развитие": "Tourism & Development",
  "У вас небольшой город, {n0} жителей и десять лет управления ({n1} месяцев). Ваша задача — поддерживать жизнеспособность города и благополучие людей.": "You lead a small town of {n0} residents over ten years of governance ({n1} months). Maintain viability and resident wellbeing.",
  "Узнать ➔ Решить ➔ Подождать ➔ Проверить": "Inquire ➔ Decide ➔ Wait ➔ Verify",
  "Управление": "Governance",
  "Уравнения оригинального компьютерного симулятора {n0}-х годов не опубликованы; мы воссоздали качественную системную динамику, строго следуя описанным в книге закономерностям.": "The original {n0}s simulation equations were never published; we recreated qualitative system dynamics adhering strictly to relationships described in the book.",
  "Фабрика, жители, казна — части одной связанной системы.": "Factory, residents, and treasury are parts of a single coupled system.",
  "Хроника последнего хода": "Latest Turn Chronicle",
  "Цель:": "Goal:",
  "Численные коэффициенты износа оборудования, производительности и спроса.": "Numerical parameters for machine wear, productivity, and market demand.",
  "Что действительно изменилось в системе?": "What truly changed in the system?",
  "Что происходит в подразделениях города?": "What is happening across municipal departments?",
  "Что смоделировано в этой версии": "What is Modeled in this Version",
  "Что сохранено из первоисточника": "What is Preserved from the Primary Source",
  "Широкие полномочия бургомистра и горизонт {n0} лет ({n1} месяцев).": "Broad mayoral powers with a horizon of {n0} years ({n1} months).",
  "Экспортировать снимок партии в JSON": "Export session snapshot to JSON",
  "Это разбор событий учебной модели, а не оценка ваших личных способностей. В книге «Логика неудачи» даже опытные политики и ученые совершали похожие системные ошибки. Ценность симулятора — в возможности исследовать последствия без риска для реальных людей.": "This debrief reviews outcomes of an educational model, not your personal worth. In “The Logic of Failure”, experienced leaders and scientists committed identical systemic misjudgments. The value lies in exploring consequences risk-free.",
  "до нового решения. Налог пополняет казну, но снижает привлекательность города. Обслуживание компенсирует износ оборудования фабрики. Услуги поддерживают медицину и уровень жизни.": "until revised. Taxes fund the treasury but diminish town appeal. Maintenance offsets factory equipment decay. Services uphold healthcare and living standards.",
  "и требует времени: муниципальное жилье строится {n0} месяцев ({n1} мест), модернизация фабрики длится {n2} месяцев, туристическая инфраструктура строится {n3} месяцев ({n4} мест). За ходом работ можно следить в панели «В работе».": "and requires time: municipal housing takes {n0} months ({n1} beds), factory modernization lasts {n2} months, and tourist facilities take {n3} months ({n4} beds). Track progress in the “In Progress” section.",
  "⏳ Оборудование фабрики ≥ {n0}%": "⏳ Factory Equipment ≥ {n0}%",
  "⏳ Промежуточный срез сценария": "⏳ Interim Scenario Check",
  "⏳ Удовлетворенность жителей ≥ {n0}%": "⏳ Resident Wellbeing ≥ {n0}%",
  "⏳ лаг": "⏳ delay",
  "⚖️ Балансирующий контур (B) · ⏳ Временной лаг (delay)": "⚖️ Balancing Loop (B) · ⏳ Time Delay",
  "⚠️ Если фабрика не способна выпустить столько часов из-за станков, спрос останется нереализованным.": "⚠️ If factory equipment bottlenecks watch output, excess demand will remain unfulfilled.",
  "⚠️ Маркус (Ловушка)": "⚠️ Marcus (Trap)",
  "⚠️ Нет существенных рисков.": "⚠️ No significant risks.",
  "⚠️ Нет.": "⚠️ None.",
  "⚠️ Низкий риск оттока.": "⚠️ Low emigration risk.",
  "⚠️ Риск деградации социальной среды.": "⚠️ Risk of social environment decay.",
  "⚠️ Траектория Маркуса (Баллистический стиль)": "⚠️ Marcus's Trajectory (Ballistic Style)",
  "⚠️ Умеренный риск.": "⚠️ Moderate risk.",
  "⚠️ Эффект проявляется медленно (инерция системы), не ждите мгновенной отдачи через месяц.": "⚠️ Effect emerges slowly (system inertia); do not expect overnight shifts in one month.",
  "⚡ Вызов Дёрнера: Преодоление ловушек": "⚡ Dörner's Challenge: Overcoming Traps",
  "⚡ Ежемесячные вложения: {n0} тыс. марок.": "⚡ Monthly investment: {n0}k Marks.",
  "⚡ Ежемесячные расходы казны: {n0} тыс. марок (потребность города: ~{n1} тыс.).": "⚡ Monthly treasury expenditure: {n0}k Marks (city baseline requirement: ~{n1}k).",
  "⚡ Около {n0} тыс. м./мес. налоговых поступлений.": "⚡ Approximately {n0}k M/mo in tax revenues.",
  "⚡ Оптимальный уровень: компенсирует износ оборудования и стабилизирует станки.": "⚡ Optimal maintenance: offsets wear and stabilizes machinery.",
  "⚡ Расходы на рекламу туризма: {n0} тыс. м./мес.": "⚡ Tourism advertising budget: {n0}k M/mo.",
  "⚡ Расходы на сбыт: {n0} тыс. м./мес. Расширяет спрос на ~{n1} часов/мес.": "⚡ Marketing budget: {n0}k M/mo. Expands demand by ~{n1} watches/mo.",
  "⚡ Фонд оплаты труда фабрики изменится пропорционально ставке ({n0}%).": "⚡ Factory payroll expands proportionally with the wage level ({n0}%).",
  "✅ Казна без хронического долга (долг = {n0})": "✅ Treasury without chronic debt (debt = {n0})",
  "❌ Оборудование фабрики ≥ {n0}%": "❌ Factory Equipment ≥ {n0}%",
  "❌ Удовлетворенность жителей ≥ {n0}%": "❌ Resident Wellbeing ≥ {n0}%",
  "🌟 Конрад (Эталон)": "🌟 Konrad (Benchmark)",
  "🌟 Эталон Конрада ({n0}-летнее гармоничное развитие)": "🌟 Konrad's Benchmark ({n0}-Year Balanced Growth)",
  "🌲 Туризм и рекреация": "🌲 Tourism & Recreation",
  "🌲 Экологическая дилемма туризма": "🌲 Ecological Tourism Dilemma",
  "🏛️ Свободное управление (Песочница)": "🏛️ Free Governance (Sandbox)",
  "🏛️ Финансы и налоги": "🏛️ Finances & Taxes",
  "🏭 Часовая фабрика и производство": "🏭 Watch Factory & Production",
  "👥 Общественные услуги и образование": "👥 Public Services & Education",
  "📖 Глава {n0}, §{n1}: участники часто завышали налоги, не замечая оттока налогоплательщиков.": "📖 Chapter {n0}, §{n1}: participants frequently inflated taxes without noticing taxpayer exodus.",
  "🔄 Повышает удовлетворенность рабочих фабрики и привлекает кадры.": "🔄 Boosts factory worker satisfaction and attracts skilled personnel.",
  "🔄 Помогает разгружать склады и увеличивает продажи.": "🔄 Helps clear inventory backlogs and drives sales.",
  "🔄 Постепенное ухудшение здоровья жителей и отток населения.": "🔄 Progressive deterioration of resident health and out-migration.",
  "🔄 Привлекает туристов (текущая вместимость отелей: {n0} мест).": "🔄 Attracts tourists (current hotel capacity: {n0} beds).",
  "🔄 Равномерный темп выпуска без простоев.": "🔄 Steady manufacturing pace without equipment stoppages.",
  "🔄 С задержкой в несколько месяцев повышает квалификацию рабочих и производительность.": "🔄 After a multi-month lag, enhances worker skills and shop-floor productivity.",
  "🔄 Умеренное влияние на располагаемый доход.": "🔄 Moderate impact on disposable household income."
};

const de = {
  "(Дневник намерений по Дёрнеру)": "(Dörner-Absichtstagebuch)",
  "(Не вызвала ли попытка решить одну проблему кризис в соседней сфере?).": "(Hat der Lösungsversuch in einem Bereich eine Krise im Nachbarbereich ausgelöst?).",
  "(Не действовать «баллистически» — всегда формулировать ожидание).": "(Kein «ballistisches Handeln» — stets konkrete Erwartungen formulieren).",
  "(Сверить факт с прогнозом и отчетом подразделения).": "(Fakten mit Prognosen und Abteilungsberichten abgleichen).",
  ". Ставка в умеренном диапазоне.": ". Steuersatz im moderaten Bereich.",
  ": бросить все средства на одну сиюминутную жалобу, пробив дыру в бюджете.": ": alle Mittel auf eine akute Beschwerde werfen und ein Haushaltsloch reißen.",
  ": начать несколько строек подряд, не дождавшись окончания {n0}-месячного срока первой.": ": mehrere Bauprojekte hintereinander starten, ohne die {n0}-monatige Bauzeit des ersten abzuwarten.",
  ": покрывать дефицит займами, пока проценты не сожрут весь бюджет.": ": Defizite über Kredite finanzieren, bis die Zinsen den gesamten Haushalt auffressen.",
  ": тратить деньги на рекламу туризма, когда в городе нет свободных гостиничных мест.": ": Geld für Tourismuswerbung ausgeben, wenn die Stadt keine freien Gästebetten hat.",
  "{n0} из {n1} целей выполнено ({n2}%)": "{n0} von {n1} Zielen erreicht ({n2}%)",
  "{n0} мес. · Высокая": "{n0} Mon. · Hoch",
  "{n0} мес. · Средняя": "{n0} Mon. · Mittel",
  "{n0} мес. · Стандартная": "{n0} Mon. · Standard",
  "{n0} мес. · Экстремальная": "{n0} Mon. · Extrem",
  "«Долговая петля»": "«Schuldenspirale»",
  "«Жилищный вопрос спокоен: вместимость фонда {n0} мест, свободно {n1} квартир. Дефицита нет».": "«Die Wohnsituation ist stabil: Gesamtkapazität {n0} Plätze, {n1} Wohnungen frei. Kein Mangel.»",
  "«Нетерпеливое перерегулирование»": "«Ungeduldige Übersteuerung»",
  "«Рекламный мираж»": "«Werbetrugbild»",
  "«Синдром ремонтника»": "«Reparaturdienst-Verhalten»",
  "«Социальный климат благоприятный: благополучие {n0}/{n1}. Рабочие довольны условиями ({n2}), семьи чувствуют заботу ({n3}), пожилые спокойны ({n4})».": "«Das soziale Klima ist günstig: Wohlbefinden bei {n0}/{n1}. Arbeiter zufrieden ({n2}), Familien umsorgt ({n3}), Senioren beruhigt ({n4}).»",
  "«Туристический сектор работает в спокойном режиме: вместимость {n0} мест, принято {n1} гостей. Спрос составляет {n2} чел.».": "«Der Tourismussektor arbeitet stabil: Kapazität {n0} Betten, {n1} Gäste empfangen. Nachfrage liegt bei {n2} Personen.»",
  "«Фабрика работает стабильно. Станки требуют регулярного внимания, запасы на складе соответствуют обычному месячному обороту».": "«Die Uhrenfabrik arbeitet stabil. Maschinen benötigen regelmäßige Wartung, das Lager entspricht dem üblichen Monatsdurchlauf.»",
  "«Финансовое положение устойчиво. Долг города: {n0} тыс. м., казна: {n1} тыс. м. Текущий баланс под контролем».": "«Die Finanzlage ist solide. Stadtschulden: {n0} Tsd. M., Kasse: {n1} Tsd. M. Der laufende Saldo ist unter Kontrolle.»",
  "· Сейчас:": "· Aktuell:",
  "· Финансы и миграция": "· Finanzen & Migration",
  "· каждый шаг оставляет след в системе города": "· jeder Schritt hinterlässt Spuren im Gesamtsystem der Stadt",
  "Администрация развернула агрессивную рекламу туризма (бюджет {n0} тыс./мес.), однако гостиничных мест всего {n1}, а в городе возник дефицит жилья ({n2} мест при населении {n3}). Балансируйте развитие рекреации и базовые потребности горожан.": "Die Stadtverwaltung startete aggressive Tourismuswerbung ({n0} Tsd. M./Monat Etat), doch es gibt nur {n1} Betten, während Wohnungsnot ({n2} Plätze bei {n3} Einwohnern) entstand. Halten Sie Erholung und Grundbedürfnisse im Gleichgewicht.",
  "Анатомия системных связей": "Anatomie systemischer Vernetzungen",
  "Баланс: {n0} тыс. м. · Долг: {n1} тыс.": "Saldo: {n0} Tsd. M. · Schulden: {n1} Tsd.",
  "Балансирующий": "Ausgleichend",
  "Бутылочное горлышко туризма": "Tourismus-Flaschenhals",
  "В «Решениях» настройте ползунки, прочитайте What-If подсказки о прямых эффектах и системных рисках.": "Passen Sie unter «Entscheidungen» die Regler an und prüfen Sie die Was-wäre-wenn-Vorschau zu Wirkungen und Risiken.",
  "В кабинет бургомистра": "Zum Bürgermeister-Cockpit",
  "В книге «Логика неудачи» участники терпели крах, пытаясь воздействовать на одну переменную и игнорируя замкнутые петли обратной связи.": "In «Die Logik des Mißlingens» scheiterten Versuchspersonen, indem sie isolierte Variablen steuerten und Regelkreise ignorierten.",
  "Ваш город · Ваши решения": "Ihre Stadt · Ihre Entscheidungen",
  "Ваш стиль управления Лоххаузеном отличается высокой системной дисциплиной. Вы избежали типичных психологических ловушек, описанных Дёрнером, и продемонстрировали способность мыслить контурами обратной связи.": "Ihr Führungsstil in Lohhausen zeichnet sich durch hohe Systemdisziplin aus. Sie vermieden Dörners typische Denkfallen und dachten in Regelkreisen.",
  "Вдумчивое системное управление:": "Umsichtige Systemführung:",
  "Вопросы для саморефлексии:": "Fragen zur Selbstreflexion:",
  "Время идет только по кнопкам «Следующий месяц» и «{n0} месяца». Пока вы анализируете доклады советников или настраиваете политику, город ждет.": "Die Zeit vergeht nur über «Nächster Monat» und «+{n0} Monate». Während Sie Berichte studieren oder Politiken anpassen, wartet die Stadt.",
  "Вы проявили терпение, учитывали временные лаги и контролировали последствия решений через доклады подразделений.": "Sie bewiesen Geduld, berücksichtigten Zeitverzögerungen und kontrollierten Maßnahmen über Abteilungsberichte.",
  "Выполнено: {n0} из {n1} ({n2}%)": "Abgeschlossen: {n0} von {n1} ({n2}%)",
  "ГОРОДСКИЕ СЛУЖБЫ": "STÄDTISCHE DIENSTE",
  "Главные когнитивные ловушки Дёрнера": "Dörners zentrale Denkfallen",
  "Главы {n0}–{n1} «Логики неудачи»; немецкое издание Rowohlt, {n2}: с. {n3}–{n4}.": "Kapitel {n0}–{n1} von «Die Logik des Mißlingens»; Rowohlt {n2}: S. {n3}–{n4}.",
  "Горизонт — {n0} г. ({n1} мес.)": "Zeithorizont — {n0} J. ({n1} Mon.)",
  "Город вошел в фазу нестабильности: налоги завышены до {n0}%, рабочие недовольны низкими зарплатами, а инфраструктура запущена. Проявите комплексное мышление, избегая синдрома ремонтника и нетерпеливого перерегулирования.": "Die Stadt geriet in eine Instabilitätsphase: Steuern auf {n0}% überhöht, Arbeiter verstimmt über Niedriglöhne, Infrastruktur vernachlässigt. Denken Sie vernetzt und vermeiden Sie Reparaturdienst-Verhalten sowie Übersteuerung.",
  "Групповой нелинейный расчет удовлетворенности (рабочие, семьи, пожилые).": "Gruppenspezifische nichtlineare Zufriedenheitsrechnung (Arbeiter, Familien, Senioren).",
  "Датированная отчетность и система советов подразделений.": "Datierte Lageberichte und städtisches Beratersystem.",
  "Датированные отчеты — отражение неполноты информации в эксперименте Дёрнера. Спрашивайте то, что нужно для проверки конкретной гипотезы.": "Datierte Berichte spiegeln die Unvollständigkeit von Information im Experiment wider. Fordern Sie gezielt an, was Hypothesen prüft.",
  "Действующая политика": "Aktuelle Richtlinie",
  "Держите налоги в умеренном диапазоне ({n0}–{n1}%), чтобы не подавлять активность.": "Halten Sie Steuern in einem moderaten Bereich ({n0}–{n1}%), um die Aktivität nicht abzuwürgen.",
  "Для осмысленного опыта двигайтесь по одному месяцу: «Хроника хода» сразу объяснит, что и почему изменилось.": "Für eine fundierte Lernerfahrung schreiten Sie monatweise voran: Die «Rundenchronik» erklärt Ursachen und Wirkungen.",
  "Добавляет {n0} гостиничных мест через {n1} месяцев. Создает физическую базу для приема гостей города и доходов казны.": "Schafft {n0} Gästebetten nach {n1} Monaten. Bildet die materielle Basis für Besucher und städtische Einnahmen.",
  "Долговая спираль": "Schuldenspirale",
  "Доходы бюджета": "Haushaltseinnahmen",
  "ЕЖЕМЕСЯЧНЫЕ СТАВКИ": "MONATLICHE SÄTZE",
  "Жилье и город": "Wohnen & Stadt",
  "Жильё": "Wohnen",
  "Запас жилья умеренный (~{n0} мест). С учетом {n1}-месячного строительного лага стоит готовить расширение заранее.": "Wohnraumreserve ist mäßig (~{n0} Plätze). Wegen der {n1}-monatigen Bauverzögerung frühzeitig planen.",
  "ИЛЛЮСТРАТИВНЫЕ АРХЕТИПЫ ПО КНИГЕ ДЁРНЕРА": "ILLUSTRATIVE ARCHETYPEN NACH DÖRNERS BUCH",
  "ИТОГИ СЦЕНАРИЯ: Свободное управление (Песочница)": "SZENARIO-ERGEBNIS: Freies Spiel (Sandkasten)",
  "Игрок (Вы)": "Spieler (Sie)",
  "Из книги Дёрнера": "Aus Dörners Buch",
  "Изучайте связи. Учитывайте время и задержки.": "Erkennen Sie Vernetzungen. Berücksichtigen Sie Zeit und Verzögerungen.",
  "Изучите доклады советников.": "Studieren Sie die Beraterberichte.",
  "Индекс благополучия жителей (%)": "Wohlbefindensindex der Bürger (%)",
  "Инженерные допущения": "Technische Annahmen",
  "Кабинет бургомистра": "Bürgermeister-Cockpit",
  "Кабинет советников": "Beraterkabinett",
  "Казна и налоги": "Kasse & Steuern",
  "Какие побочные эффекты проявились?": "Welche Nebenwirkungen zeigten sich?",
  "Какое из принятых вами решений принесло максимальный отложенный эффект — позитивный или разрушительный?": "Welche Entscheidung hatte die stärkste verzögerte Wirkung — positiv oder zerstörerisch?",
  "Какую главную цель вы преследовали в этой партии, и менялась ли она по ходу времени?": "Welches Hauptziel verfolgten Sie und veränderte es sich im Laufe der Zeit?",
  "Классический эксперимент Лоххаузена {n0} года": "Klassisches Lohhausen-Experiment von {n0}",
  "Конрад (Системный мыслитель)": "Konrad (Systemdenker)",
  "ЛОХХАУЗЕН · СИМУЛЯТОР СИСТЕМНОГО МЫШЛЕНИЯ ПО ДЁРНЕРУ": "LOHHAUSEN · SYSTEMDYNAMIK-SIMULATOR NACH DÖRNER",
  "Лоххаузен ожидает первых решений. Ознакомьтесь с докладами подразделений и определите приоритеты.": "Lohhausen erwartet erste Entscheidungen. Prüfen Sie die Lageberichte und setzen Sie Prioritäten.",
  "Лоххаузен превратился в самоподдерживающийся цветущий город с максимальным индексом благополучия ({n0}).": "Lohhausen wurde zu einer blühenden, selbsttragenden Stadt mit höchstem Wohlbefinden ({n0}).",
  "Маленький город: около {n0} жителей в немецких среднегорьях.": "Kleinstadt: rund {n0} Einwohner in einer deutschen Mittelgebirgsregion.",
  "Мест: {n0} · Посетителей: {n1}": "Plätze: {n0} · Besucher: {n1}",
  "Миграция": "Migration",
  "Муниципальная часовая фабрика — основа городской экономики.": "Die städtische Uhrenfabrik ist das Fundament der städtischen Wirtschaft.",
  "На главном экране кабинета советники (Герр Краузе, Фрау Вебер, Герр Бауэр, Доктор Франк, Фрау Линдеманн) сообщают о текущих узких местах.": "Im Bürgermeister-Cockpit melden die Berater (Herr Krause, Frau Weber, Herr Bauer, Dr. Frank, Frau Lindemann) Engpässe.",
  "Нажмите на район города, чтобы открыть отчет подразделения": "Klicken Sie auf ein Stadtviertel, um den Lagebericht zu öffnen",
  "Накопление отложенных дефицитов, резкий износ инфраструктуры и финансовый кризис во второй половине срока.": "Akkumulation versteckter Defizite, schwerer Verfall der Infrastruktur und Finanzkrise in der zweiten Amtszeit.",
  "Налоговая база": "Steuerbasis",
  "Налоговая петля оттока": "Steuer-Abwanderungsschleife",
  "Например: увеличить ремонт станков до {n0} тыс.; через полгода проверить выпуск и прибыль фабрики.": "Beispiel: Maschinenwartung auf {n0} Tsd. erhöhen; nach sechs Monaten Ausstoß und Gewinn prüfen.",
  "Начало": "Start",
  "Неполнота информации, обратные связи, временные задержки и конфликты целей.": "Unvollständige Information, Rückkopplungen, Zeitverzögerungen und Zielkonflikte.",
  "Новая политика начнет действовать со следующего хода.": "Die neue Richtlinie tritt ab dem nächsten Zug in Kraft.",
  "Обновить все службы": "Alle Dienste aktualisieren",
  "Обновить отчеты всех {n0} подразделений": "Lageberichte aller {n0} Abteilungen aktualisieren",
  "Оборудование градообразующего часового завода изношено до критических {n0}%. Накоплен краткосрочный долг в {n1} тыс. марок, а свободных средств в казне осталось всего {n2} тыс. Предотвратите остановку завода и верните рентабельность.": "Die Maschinen der zentralen Uhrenfabrik sind auf kritische {n0}% verschlissen. Die kurzfristigen Schulden betragen {n1} Tsd. Mark bei nur {n2} Tsd. verbliebenen Barmitteln. Verhindern Sie den Stillstand und sichern Sie die Rentabilität.",
  "Оборудование изношено ({n0}%). Проект добавит {n1} пунктов оборудования (~{n2}%) и повысит производительность линии за {n3} месяцев.": "Maschinen sind abgenutzt ({n0}%). Projekt bringt +{n1} Punkte Maschinenpark (~{n2}%) und steigert die Kapazität in {n3} Monaten.",
  "Один управленческий цикл": "Ein Steuerungszyklus",
  "Осталось месяцев: {n0}": "Verbleibende Monate: {n0}",
  "Отчет службы": "Lagebericht",
  "ПРИЧИННО-СЛЕДСТВЕННЫЙ АНАЛИЗ": "URSACHEN-WIRKUNGS-ANALYSE",
  "Петля износа станков": "Maschinenverschleiß-Regelkreis",
  "Петля привлекательности и задержки жилья": "Attraktivitäts- und Wohnungsverzögerungsschleife",
  "Планомерное инвестирование из операционной прибыли, заблаговременное строительство жилья, удержание безработицы ниже {n0} человек.": "Systematische Investitionen aus laufendem Überschuss, vorausschauender Wohnungsbau und Arbeitslosigkeit unter {n0} Personen.",
  "По книге Дитриха Дёрнера «Логика неудачи» (Die Logik des Mißlingens). Здесь можно исследовать описанные в книге системные связи.": "Nach Dietrich Dörners Buch «Die Logik des Mißlingens». Hier können die beschriebenen systemischen Zusammenhänge erforscht werden.",
  "Повышение налога кажется легким способом закрыть дыру в казне. Однако бремя снижает привлекательность Лоххаузена: жители начинают уезжать, число налогоплательщиков падает, и в итоге налоговые поступления снова снижаются, несмотря на высокую ставку.": "Steuererhöhungen wirken wie eine einfache Lösung für Haushaltslöcher. Die Abgabenlast mindert jedoch die Attraktivität: Bürger wandern ab, die Steuerbasis schrumpft, und die Einnahmen sinken trotz hoher Sätze.",
  "Поддерживайте расходы на обучение для планомерного роста квалификации рабочих.": "Sichern Sie Ausbildungsbudgets für kontinuierliche Weiterbildung der Fachkräfte.",
  "Положение в вашем Лоххаузене прямо сейчас:": "Lage in Ihrem Lohhausen zum jetzigen Zeitpunkt:",
  "Посмотреть полный финансовый отчет": "Vollständigen Finanzbericht ansehen",
  "Привлекательность": "Attraktivität",
  "Применяется каждый шаг": "Wird jeden Zug angewendet",
  "Принятие решений без последующей проверки эффектов; пренебрежение регулярными отчетами служб; позднее обнаружение скрытых кризисов.": "Handeln ohne Wirkungskontrolle; Vernachlässigung regelmäßiger Berichte; verspätetes Erkennen verdeckter Krisen.",
  "Принять решения": "Entscheidungen anwenden",
  "Пробел": "Leertaste",
  "Проверьте гипотезу.": "Überprüfen Sie die Hypothese.",
  "Проект оплачивается сразу и один раз": "Projekt wird einmalig im Voraus bezahlt",
  "Производство": "Produktion",
  "Процентный долг города ({n0}% в месяц) и кассовый баланс.": "Verzinsliche Stadtschulden ({n0}% pro Monat) und Kassenbestand.",
  "Пять критических переменных: финансы, производство, работа, жилье и благополучие.": "Fünf kritische Variablen: Finanzen, Produktion, Arbeit, Wohnen und Wohlbefinden.",
  "Развитие туризма требует синхронного роста гостиниц, рекламы и доступных рабочих рук.": "Tourismusentwicklung erfordert synchronen Ausbau von Betten, Werbung und verfügbaren Arbeitskräften.",
  "Располагаемый доход": "Verfügbares Einkommen",
  "Реактивная ловушка": "Reaktive Falle",
  "Решения и проекты": "Entscheidungen & Projekte",
  "СИСТЕМНЫЕ НАБЛЮДЕНИЯ ПО ВАШЕЙ ПАРТИИ": "SYSTEMISCHE BEOBACHTUNGEN IHRER PARTIE",
  "СНАЧАЛА — ВОПРОСЫ И АНАЛИЗ": "ZUERST — ANALYSE & FRAGEN",
  "СЦЕНАРИЙ: Свободное управление (Песочница)": "SZENARIO: Freies Spiel (Sandkasten)",
  "Свободно мест: {n0} из {n1}": "Freie Plätze: {n0} von {n1}",
  "Сводка на главной показывает общее состояние. Подробный отчет раскрывает причины и скрытые механизмы.": "Die Übersicht zeigt den Gesamtzustand. Detaillierte Berichte legen Ursachen und verdeckte Mechanismen offen.",
  "Сделайте ход.": "Führen Sie einen Zug aus.",
  "Сейчас налоговая ставка составляет": "Der aktuelle Steuersatz beträgt",
  "Системный радар здоровья города": "Systemisches Stadtgesundheits-Radar",
  "Системный эталон": "Systemischer Maßstab",
  "Скачать подробный аналитический отчет": "Ausführlichen Analysebericht herunterladen",
  "Следите за балансом между объемом выпуска и внешним спросом на часы.": "Achten Sie auf das Gleichgewicht zwischen Uhrenproduktion und externer Nachfrage.",
  "Службы": "Dienste",
  "Службы реагируют на реальные изменения в городе": "Dienste reagieren auf reale Veränderungen in der Stadt",
  "Случалось ли так, что меры по спасению одной сферы неожиданно разрушали баланс в соседней?": "Führten Rettungsmaßnahmen in einem Bereich unerwartet zu Schieflagen im Nachbarbereich?",
  "Сопоставьте реальный факт с ожиданием. Если что-то пошло не так, исследуйте обратные связи в разделе «Анатомия связей».": "Gleichen Sie Ergebnisse mit Erwartungen ab. Bei unerwarteten Abweichungen Regelkreise in der «Anatomie der Vernetzung» untersuchen.",
  "Сравнение с модельными профилями поведения": "Vergleich mit modellhaften Verhaltensprofilen",
  "Сравнение с эталонами Дёрнера: Индекс благополучия жителей": "Vergleich mit Dörner-Maßstäben: Wohlbefindensindex der Bürger",
  "Стандартная": "Standard",
  "Стандартные стартовые условия города Лоххаузен. Горизонт планирования — {n0} лет ({n1} месяцев). Ваша задача — развивать город, соблюдая баланс между экономикой фабрики, благополучием жителей и устойчивостью казны.": "Standard-Startbedingungen für Lohhausen. Planungshorizont: {n0} Jahre ({n1} Monate). Entwickeln Sie die Stadt im Gleichgewicht von Uhrenfabrik, Bürgerwohl und Kassenstabilität.",
  "Станки: {n0}% · Выпуск: {n1} шт.": "Maschinen: {n0}% · Ausstoß: {n1} Stk.",
  "Стартовая диспозиция Лоххаузена": "Ausgangslage von Lohhausen",
  "Стратегия:": "Strategie:",
  "Строительство жилья: {n0} месяцев лага и {n1} новых мест.": "Wohnungsbau: {n0} Monate Verzögerung und {n1} neue Plätze.",
  "Сформулируйте изменение.": "Begründen Sie die Änderung.",
  "Текущая политика действует каждый месяц. Проекты оплачиваются один раз и дают результат после завершения срока строительства.": "Laufende Richtlinien gelten monatlich. Projekte werden einmalig bezahlt und wirken nach Ablauf der Bauzeit.",
  "Траектории Конрада (системный эталон) и Маркуса (реактивная ловушка) построены на основе описаний из глав {n0} и {n1} книги «Логика неудачи» как дидактические ориентиры для самоанализа.": "Die Trajektorien von Konrad (systemischer Maßstab) und Marcus (reaktive Falle) basieren auf Kapitel {n0} und {n1} von «Die Logik des Mißlingens» als didaktische Orientierung.",
  "Требование: {n0} · Результат:": "Vorgabe: {n0} · Ergebnis:",
  "Три вопроса рефлексии Дёрнера": "Dörners drei Reflexionsfragen",
  "Туризм и развитие": "Tourismus & Entwicklung",
  "У вас небольшой город, {n0} жителей и десять лет управления ({n1} месяцев). Ваша задача — поддерживать жизнеспособность города и благополучие людей.": "Sie führen eine Kleinstadt mit {n0} Einwohnern über zehn Amtsjahre ({n1} Monate). Sichern Sie Lebensfähigkeit und Wohlbefinden.",
  "Узнать ➔ Решить ➔ Подождать ➔ Проверить": "Erkunden ➔ Entscheiden ➔ Abwarten ➔ Prüfen",
  "Управление": "Steuerung",
  "Уравнения оригинального компьютерного симулятора {n0}-х годов не опубликованы; мы воссоздали качественную системную динамику, строго следуя описанным в книге закономерностям.": "Die Gleichungen der Originalsimulation der {n0}er-Jahre wurden nie veröffentlicht; wir haben die qualitative Systemdynamik nach den Buchbeschreibungen rekonstruiert.",
  "Фабрика, жители, казна — части одной связанной системы.": "Uhrenfabrik, Bürger und Kasse sind Teile eines vernetzten Gesamtsystems.",
  "Хроника последнего хода": "Chronik des letzten Zugs",
  "Цель:": "Ziel:",
  "Численные коэффициенты износа оборудования, производительности и спроса.": "Numerische Parameter für Maschinenverschleiß, Produktivität und Nachfrage.",
  "Что действительно изменилось в системе?": "Was hat sich im System wirklich verändert?",
  "Что происходит в подразделениях города?": "Was geschieht in den städtischen Dienststellen?",
  "Что смоделировано в этой версии": "Was in dieser Version modelliert ist",
  "Что сохранено из первоисточника": "Was aus dem Original übernommen wurde",
  "Широкие полномочия бургомистра и горизонт {n0} лет ({n1} месяцев).": "Weitreichende Befugnisse des Bürgermeisters und ein Zeithorizont von {n0} Jahren ({n1} Monaten).",
  "Экспортировать снимок партии в JSON": "Sitzungs-Snapshot als JSON exportieren",
  "Это разбор событий учебной модели, а не оценка ваших личных способностей. В книге «Логика неудачи» даже опытные политики и ученые совершали похожие системные ошибки. Ценность симулятора — в возможности исследовать последствия без риска для реальных людей.": "Diese Auswertung analysiert ein didaktisches Modell, keine persönliche Eignung. In «Die Logik des Mißlingens» machten erfahrene Fachleute dieselben Fehler. Der Wert liegt im risikofreien Lernen.",
  "до нового решения. Налог пополняет казну, но снижает привлекательность города. Обслуживание компенсирует износ оборудования фабрики. Услуги поддерживают медицину и уровень жизни.": "bis zur Neufestsetzung. Steuern füllen die Kasse, mindern aber die Attraktivität. Wartung bremst Maschinenverschleiß. Dienste sichern Gesundheit und Lebensstandard.",
  "и требует времени: муниципальное жилье строится {n0} месяцев ({n1} мест), модернизация фабрики длится {n2} месяцев, туристическая инфраструктура строится {n3} месяцев ({n4} мест). За ходом работ можно следить в панели «В работе».": "und braucht Zeit: Wohnungsbau dauert {n0} Monate ({n1} Plätze), Modernisierung {n2} Monate, Tourismusausbau {n3} Monate ({n4} Plätze). Baufortschritt unter «In Arbeit» verfolgen.",
  "⏳ Оборудование фабрики ≥ {n0}%": "⏳ Fabrikausstattung ≥ {n0}%",
  "⏳ Промежуточный срез сценария": "⏳ Zwischenstand des Szenarios",
  "⏳ Удовлетворенность жителей ≥ {n0}%": "⏳ Bürgerzufriedenheit ≥ {n0}%",
  "⏳ лаг": "⏳ Verzögerung",
  "⚖️ Балансирующий контур (B) · ⏳ Временной лаг (delay)": "⚖️ Ausgleichender Regelkreis (B) · ⏳ Zeitverzögerung (Delay)",
  "⚠️ Если фабрика не способна выпустить столько часов из-за станков, спрос останется нереализованным.": "⚠️ Wenn der Maschinenpark die Uhrenproduktion drosselt, bleibt die Nachfrage ungedeckt.",
  "⚠️ Маркус (Ловушка)": "⚠️ Marcus (Falle)",
  "⚠️ Нет существенных рисков.": "⚠️ Keine wesentlichen Risiken.",
  "⚠️ Нет.": "⚠️ Keine.",
  "⚠️ Низкий риск оттока.": "⚠️ Geringes Abwanderungsrisiko.",
  "⚠️ Риск деградации социальной среды.": "⚠️ Gefahr einer Verschlechterung des sozialen Gefüges.",
  "⚠️ Траектория Маркуса (Баллистический стиль)": "⚠️ Marcus' Trajektorie (Ballistisches Verhalten)",
  "⚠️ Умеренный риск.": "⚠️ Mäßiges Risiko.",
  "⚠️ Эффект проявляется медленно (инерция системы), не ждите мгновенной отдачи через месяц.": "⚠️ Wirkung setzt träge ein (Systemträgheit); erwarten Sie keinen Durchbruch nach einem Monat.",
  "⚡ Вызов Дёрнера: Преодоление ловушек": "⚡ Dörner-Herausforderung: Denkfallen überwinden",
  "⚡ Ежемесячные вложения: {n0} тыс. марок.": "⚡ Monatliche Investition: {n0} Tsd. Mark.",
  "⚡ Ежемесячные расходы казны: {n0} тыс. марок (потребность города: ~{n1} тыс.).": "⚡ Monatliche Kassenaufwendungen: {n0} Tsd. Mark (Bedarf der Stadt: ~{n1} Tsd.).",
  "⚡ Около {n0} тыс. м./мес. налоговых поступлений.": "⚡ Rund {n0} Tsd. M./Monat Steuereinnahmen.",
  "⚡ Оптимальный уровень: компенсирует износ оборудования и стабилизирует станки.": "⚡ Optimales Niveau: gleicht Verschleiß aus und stabilisiert die Maschinen.",
  "⚡ Расходы на рекламу туризма: {n0} тыс. м./мес.": "⚡ Ausgaben für Tourismuswerbung: {n0} Tsd. M./Monat.",
  "⚡ Расходы на сбыт: {n0} тыс. м./мес. Расширяет спрос на ~{n1} часов/мес.": "⚡ Vertriebsbudget: {n0} Tsd. M./Monat. Steigert die Nachfrage um ~{n1} Uhren/Monat.",
  "⚡ Фонд оплаты труда фабрики изменится пропорционально ставке ({n0}%).": "⚡ Lohnsumme der Uhrenfabrik verändert sich proportional zum Satz ({n0}%).",
  "✅ Казна без хронического долга (долг = {n0})": "✅ Kasse ohne dauerhafte Schulden (Schulden = {n0})",
  "❌ Оборудование фабрики ≥ {n0}%": "❌ Fabrikausstattung ≥ {n0}%",
  "❌ Удовлетворенность жителей ≥ {n0}%": "❌ Bürgerzufriedenheit ≥ {n0}%",
  "🌟 Конрад (Эталон)": "🌟 Konrad (Maßstab)",
  "🌟 Эталон Конрада ({n0}-летнее гармоничное развитие)": "🌟 Konrads Maßstab ({n0}-jährige harmonische Entwicklung)",
  "🌲 Туризм и рекреация": "🌲 Tourismus & Erholung",
  "🌲 Экологическая дилемма туризма": "🌲 Ökologisches Tourismus-Dilemma",
  "🏛️ Свободное управление (Песочница)": "🏛️ Freies Spiel (Sandkasten)",
  "🏛️ Финансы и налоги": "🏛️ Finanzen & Steuern",
  "🏭 Часовая фабрика и производство": "🏭 Uhrenfabrik & Produktion",
  "👥 Общественные услуги и образование": "👥 Öffentliche Dienste & Bildung",
  "📖 Глава {n0}, §{n1}: участники часто завышали налоги, не замечая оттока налогоплательщиков.": "📖 Kapitel {n0}, §{n1}: Versuchspersonen erhöhten oft Steuern, ohne die Abwanderung zu bemerken.",
  "🔄 Повышает удовлетворенность рабочих фабрики и привлекает кадры.": "🔄 Steigert die Zufriedenheit der Fabrikarbeiter und zieht Fachkräfte an.",
  "🔄 Помогает разгружать склады и увеличивает продажи.": "🔄 Baut Lagerbestände ab und kurbelt Verkäufe an.",
  "🔄 Постепенное ухудшение здоровья жителей и отток населения.": "🔄 Allmähliche Verschlechterung der Gesundheit und Abwanderung.",
  "🔄 Привлекает туристов (текущая вместимость отелей: {n0} мест).": "🔄 Zieht Touristen an (aktuelle Hotelkapazität: {n0} Betten).",
  "🔄 Равномерный темп выпуска без простоев.": "🔄 Gleichmäßiger Fertigungsrhythmus ohne Ausfälle.",
  "🔄 С задержкой в несколько месяцев повышает квалификацию рабочих и производительность.": "🔄 Steigert mit einigen Monaten Verzögerung die Fachkompetenz und Produktivität.",
  "🔄 Умеренное влияние на располагаемый доход.": "🔄 Mäßiger Einfluss auf das verfügbare Einkommen."
};

const fr = {
  "(Дневник намерений по Дёрнеру)": "(Journal des intentions selon Dörner)",
  "(Не вызвала ли попытка решить одну проблему кризис в соседней сфере?).": "(La tentative de résoudre un problème a-t-elle déclenché une crise dans un domaine voisin ?).",
  "(Не действовать «баллистически» — всегда формулировать ожидание).": "(Éviter toute action balistique — toujours formuler une attente explicite).",
  "(Сверить факт с прогнозом и отчетом подразделения).": "(Comparer le résultat réel aux prévisions et aux rapports de service).",
  ". Ставка в умеренном диапазоне.": ". Taux d'imposition dans une fourchette modérée.",
  ": бросить все средства на одну сиюминутную жалобу, пробив дыру в бюджете.": ": consacrer toutes les ressources à une plainte ponctuelle, créant un gouffre budgétaire.",
  ": начать несколько строек подряд, не дождавшись окончания {n0}-месячного срока первой.": ": lancer plusieurs chantiers d'affilée sans attendre la fin du délai de {n0} mois du premier.",
  ": покрывать дефицит займами, пока проценты не сожрут весь бюджет.": ": combler les déficits par l'emprunt jusqu'à ce que les intérêts absorbent tout le budget.",
  ": тратить деньги на рекламу туризма, когда в городе нет свободных гостиничных мест.": ": dépenser pour la promotion touristique alors que la ville n'a aucun lit d'hôtel disponible.",
  "{n0} из {n1} целей выполнено ({n2}%)": "{n0} sur {n1} objectifs atteints ({n2} %)",
  "{n0} мес. · Высокая": "{n0} mois · Élevée",
  "{n0} мес. · Средняя": "{n0} mois · Moyenne",
  "{n0} мес. · Стандартная": "{n0} mois · Standard",
  "{n0} мес. · Экстремальная": "{n0} mois · Extrême",
  "«Долговая петля»": "« Boucle de la dette »",
  "«Жилищный вопрос спокоен: вместимость фонда {n0} мест, свободно {n1} квартир. Дефицита нет».": "« La situation du logement est stable : capacité de {n0} places, {n1} logements vacants. Pas de pénurie. »",
  "«Нетерпеливое перерегулирование»": "« Sur-régulation impatiente »",
  "«Рекламный мираж»": "« Mirage publicitaire »",
  "«Синдром ремонтника»": "« Syndrome du dépanneur »",
  "«Социальный климат благоприятный: благополучие {n0}/{n1}. Рабочие довольны условиями ({n2}), семьи чувствуют заботу ({n3}), пожилые спокойны ({n4})».": "« Le climat social est favorable : bien-être à {n0}/{n1}. Ouvriers satisfaits ({n2}), familles soutenues ({n3}), aînés sereins ({n4}). »",
  "«Туристический сектор работает в спокойном режиме: вместимость {n0} мест, принято {n1} гостей. Спрос составляет {n2} чел.».": "« Le secteur touristique fonctionne calmement : capacité {n0} places, {n1} visiteurs accueillis. Demande à {n2} pers. »",
  "«Фабрика работает стабильно. Станки требуют регулярного внимания, запасы на складе соответствуют обычному месячному обороту».": "« L'usine d'horlogerie fonctionne régulièrement. Les machines requièrent un entretien constant, les stocks correspondent au roulement mensuel habituel. »",
  "«Финансовое положение устойчиво. Долг города: {n0} тыс. м., казна: {n1} тыс. м. Текущий баланс под контролем».": "« La situation financière est saine. Dette : {n0} k M., trésorerie : {n1} k M. Solde courant sous contrôle. »",
  "· Сейчас:": "· Actuellement :",
  "· Финансы и миграция": "· Finances et migration",
  "· каждый шаг оставляет след в системе города": "· chaque étape marque le système urbain",
  "Администрация развернула агрессивную рекламу туризма (бюджет {n0} тыс./мес.), однако гостиничных мест всего {n1}, а в городе возник дефицит жилья ({n2} мест при населении {n3}). Балансируйте развитие рекреации и базовые потребности горожан.": "L'administration a déployé une promotion touristique agressive ({n0} k M./mois), mais la capacité n'est que de {n1} lits et une pénurie de logement ({n2} places pour {n3} habitants) est apparue. Équilibrez loisirs et besoins essentiels.",
  "Анатомия системных связей": "Anatomie des liens systémiques",
  "Баланс: {n0} тыс. м. · Долг: {n1} тыс.": "Solde : {n0} k M. · Dette : {n1} k",
  "Балансирующий": "Équilibrant",
  "Бутылочное горлышко туризма": "Goulot d'étranglement touristique",
  "В «Решениях» настройте ползунки, прочитайте What-If подсказки о прямых эффектах и системных рисках.": "Dans « Décisions », réglez les curseurs et lisez les aperçus What-If sur les effets directs et risques systémiques.",
  "В кабинет бургомистра": "Vers le bureau du maire",
  "В книге «Логика неудачи» участники терпели крах, пытаясь воздействовать на одну переменную и игнорируя замкнутые петли обратной связи.": "Dans « La Logique de l'échec », les participants échouaient en agissant sur une seule variable sans tenir compte des boucles de rétroaction.",
  "Ваш город · Ваши решения": "Votre ville · Vos décisions",
  "Ваш стиль управления Лоххаузеном отличается высокой системной дисциплиной. Вы избежали типичных психологических ловушек, описанных Дёрнером, и продемонстрировали способность мыслить контурами обратной связи.": "Votre gestion de Lohhausen fait preuve d'une grande discipline systémique. Vous avez évité les pièges psychologiques décrits par Dörner et raisonné en boucles de rétroaction.",
  "Вдумчивое системное управление:": "Gestion systémique réfléchie :",
  "Вопросы для саморефлексии:": "Questions d'autoréflexion :",
  "Время идет только по кнопкам «Следующий месяц» и «{n0} месяца». Пока вы анализируете доклады советников или настраиваете политику, город ждет.": "Le temps n'avance que via « Mois suivant » et « +{n0} mois ». Tant que vous examinez les rapports ou réglez les politiques, la ville attend.",
  "Вы проявили терпение, учитывали временные лаги и контролировали последствия решений через доклады подразделений.": "Vous avez fait preuve de patience, pris en compte les retards temporels et contrôlé les effets par les rapports de service.",
  "Выполнено: {n0} из {n1} ({n2}%)": "Terminé : {n0} sur {n1} ({n2} %)",
  "ГОРОДСКИЕ СЛУЖБЫ": "SERVICES MUNICIPAUX",
  "Главные когнитивные ловушки Дёрнера": "Principaux pièges cognitifs de Dörner",
  "Главы {n0}–{n1} «Логики неудачи»; немецкое издание Rowohlt, {n2}: с. {n3}–{n4}.": "Chapitres {n0}–{n1} de « La Logique de l'échec » ; édition allemande Rowohlt, {n2} : p. {n3}–{n4}.",
  "Горизонт — {n0} г. ({n1} мес.)": "Horizon — {n0} ans ({n1} mois)",
  "Город вошел в фазу нестабильности: налоги завышены до {n0}%, рабочие недовольны низкими зарплатами, а инфраструктура запущена. Проявите комплексное мышление, избегая синдрома ремонтника и нетерпеливого перерегулирования.": "La ville est entrée en crise : taxes gonflées à {n0} %, ouvriers mécontents des bas salaires, infrastructure délaissée. Pensez globalement sans tomber dans le syndrome du dépanneur ni la sur-régulation impatiente.",
  "Групповой нелинейный расчет удовлетворенности (рабочие, семьи, пожилые).": "Modèle non linéaire de satisfaction par groupe (ouvriers, familles, aînés).",
  "Датированная отчетность и система советов подразделений.": "Rapports datés et système de conseil municipal.",
  "Датированные отчеты — отражение неполноты информации в эксперименте Дёрнера. Спрашивайте то, что нужно для проверки конкретной гипотезы.": "Les rapports datés reflètent l'incomplétude de l'information chez Dörner. Ne demandez que les données utiles à vérifier une hypothèse.",
  "Действующая политика": "Politique actuelle",
  "Держите налоги в умеренном диапазоне ({n0}–{n1}%), чтобы не подавлять активность.": "Maintenez les impôts dans une fourchette modérée ({n0}–{n1} %) pour ne pas étouffer l'activité.",
  "Для осмысленного опыта двигайтесь по одному месяцу: «Хроника хода» сразу объяснит, что и почему изменилось.": "Pour une expérience enrichissante, avancez mois par mois : la « Chronique du tour » détaille chaque cause et effet.",
  "Добавляет {n0} гостиничных мест через {n1} месяцев. Создает физическую базу для приема гостей города и доходов казны.": "Ajoute {n0} lits d'hôtel en {n1} mois. Crée l'infrastructure physique pour accueillir les visiteurs et enrichir la trésorerie.",
  "Долговая спираль": "Spirale de la dette",
  "Доходы бюджета": "Recettes budgétaires",
  "ЕЖЕМЕСЯЧНЫЕ СТАВКИ": "TAUX MENSUELS",
  "Жилье и город": "Logement et ville",
  "Жильё": "Logement",
  "Запас жилья умеренный (~{n0} мест). С учетом {n1}-месячного строительного лага стоит готовить расширение заранее.": "La réserve de logement est modérée (~{n0} places). Vu le délai de chantier de {n1} mois, anticipez les travaux.",
  "ИЛЛЮСТРАТИВНЫЕ АРХЕТИПЫ ПО КНИГЕ ДЁРНЕРА": "ARCHÉTYPES DIDACTIQUES SELON LE LIVRE DE DÖRNER",
  "ИТОГИ СЦЕНАРИЯ: Свободное управление (Песочница)": "RÉSULTATS DU SCÉNARIO : Gestion libre (Bac à sable)",
  "Игрок (Вы)": "Joueur (Vous)",
  "Из книги Дёрнера": "Du livre de Dörner",
  "Изучайте связи. Учитывайте время и задержки.": "Étudiez les rétroactions. Prenez en compte le temps et les retards.",
  "Изучите доклады советников.": "Consultez les rapports des conseillers.",
  "Индекс благополучия жителей (%)": "Indice de bien-être des habitants (%)",
  "Инженерные допущения": "Hypothèses d'ingénierie",
  "Кабинет бургомистра": "Bureau du maire",
  "Кабинет советников": "Conseil des services",
  "Казна и налоги": "Trésorerie et impôts",
  "Какие побочные эффекты проявились?": "Quels effets secondaires sont apparus ?",
  "Какое из принятых вами решений принесло максимальный отложенный эффект — позитивный или разрушительный?": "Quelle décision a produit le plus grand effet différé — positif ou destructeur ?",
  "Какую главную цель вы преследовали в этой партии, и менялась ли она по ходу времени?": "Quel objectif principal avez-vous poursuivi, et a-t-il évolué au fil du temps ?",
  "Классический эксперимент Лоххаузена {n0} года": "Expérience classique de Lohhausen de {n0}",
  "Конрад (Системный мыслитель)": "Konrad (Penseur systémique)",
  "ЛОХХАУЗЕН · СИМУЛЯТОР СИСТЕМНОГО МЫШЛЕНИЯ ПО ДЁРНЕРУ": "LOHHAUSEN · SIMULATEUR DE PENSÉE SYSTÉMIQUE SELON DÖRNER",
  "Лоххаузен ожидает первых решений. Ознакомьтесь с докладами подразделений и определите приоритеты.": "Lohhausen attend vos premières décisions. Consultez les rapports et fixez vos priorités.",
  "Лоххаузен превратился в самоподдерживающийся цветущий город с максимальным индексом благополучия ({n0}).": "Lohhausen est devenue une ville florissante et autonome avec un bien-être maximal ({n0}).",
  "Маленький город: около {n0} жителей в немецких среднегорьях.": "Petite ville : environ {n0} habitants dans les moyennes montagnes allemandes.",
  "Мест: {n0} · Посетителей: {n1}": "Places : {n0} · Visiteurs : {n1}",
  "Миграция": "Migration",
  "Муниципальная часовая фабрика — основа городской экономики.": "La fabrique municipale d'horlogerie est le fondement de l'économie municipale.",
  "На главном экране кабинета советники (Герр Краузе, Фрау Вебер, Герр Бауэр, Доктор Франк, Фрау Линдеманн) сообщают о текущих узких местах.": "Dans le cockpit du maire, les conseillers (M. Krause, Mme Weber, M. Bauer, Dr Frank, Mme Lindemann) signalent les blocages.",
  "Нажмите на район города, чтобы открыть отчет подразделения": "Cliquez sur un quartier pour ouvrir le rapport de service",
  "Накопление отложенных дефицитов, резкий износ инфраструктуры и финансовый кризис во второй половине срока.": "Accumulation de déficits différés, dégradation sévère des infrastructures et crise financière en seconde moitié de mandat.",
  "Налоговая база": "Assiette fiscale",
  "Налоговая петля оттока": "Boucle fiscale d'émigration",
  "Например: увеличить ремонт станков до {n0} тыс.; через полгода проверить выпуск и прибыль фабрики.": "Exemple : porter l'entretien à {n0} k ; six mois plus tard, vérifier la production et le bénéfice de l'usine.",
  "Начало": "Début",
  "Неполнота информации, обратные связи, временные задержки и конфликты целей.": "Incomplétude de l'information, rétroactions, retards temporels et conflits d'objectifs.",
  "Новая политика начнет действовать со следующего хода.": "La nouvelle politique entrera en vigueur au prochain tour.",
  "Обновить все службы": "Actualiser tous les services",
  "Обновить отчеты всех {n0} подразделений": "Actualiser les rapports des {n0} services",
  "Оборудование градообразующего часового завода изношено до критических {n0}%. Накоплен краткосрочный долг в {n1} тыс. марок, а свободных средств в казне осталось всего {n2} тыс. Предотвратите остановку завода и верните рентабельность.": "L'équipement de l'usine d'horlogerie principale est usé à un niveau critique de {n0} %. La dette à court terme atteint {n1} k Marks avec seulement {n2} k en trésorerie. Empêchez l'arrêt de l'usine et restaurez la rentabilité.",
  "Оборудование изношено ({n0}%). Проект добавит {n1} пунктов оборудования (~{n2}%) и повысит производительность линии за {n3} месяцев.": "L'équipement est dégradé ({n0} %). Le projet apporte +{n1} points de machines (~{n2} %) et augmente le rendement en {n3} mois.",
  "Один управленческий цикл": "Un cycle de gestion",
  "Осталось месяцев: {n0}": "Mois restants : {n0}",
  "Отчет службы": "Rapport de service",
  "ПРИЧИННО-СЛЕДСТВЕННЫЙ АНАЛИЗ": "ANALYSE DE CAUSALITÉ",
  "Петля износа станков": "Boucle d'usure des machines",
  "Петля привлекательности и задержки жилья": "Boucle d'attractivité et de retard du logement",
  "Планомерное инвестирование из операционной прибыли, заблаговременное строительство жилья, удержание безработицы ниже {n0} человек.": "Investissements constants financés par les bénéfices, chantiers de logement anticipés et chômage maintenu sous {n0} personnes.",
  "По книге Дитриха Дёрнера «Логика неудачи» (Die Logik des Mißlingens). Здесь можно исследовать описанные в книге системные связи.": "D'après l'ouvrage de Dietrich Dörner « La Logique de l'échec ». Explorez ici les dynamiques systémiques décrites dans le livre.",
  "Повышение налога кажется легким способом закрыть дыру в казне. Однако бремя снижает привлекательность Лоххаузена: жители начинают уезжать, число налогоплательщиков падает, и в итоге налоговые поступления снова снижаются, несмотря на высокую ставку.": "Augmenter les impôts semble combler le trou budgétaire. Mais la charge réduit l'attractivité : les résidents partent, la base fiscale s'effondre et les recettes diminuent malgré le taux élevé.",
  "Поддерживайте расходы на обучение для планомерного роста квалификации рабочих.": "Maintenez les budgets de formation pour élever régulièrement les compétences ouvrières.",
  "Положение в вашем Лоххаузене прямо сейчас:": "Situation actuelle dans votre Lohhausen :",
  "Посмотреть полный финансовый отчет": "Consulter le rapport financier complet",
  "Привлекательность": "Attractivité",
  "Применяется каждый шаг": "Appliqué à chaque tour",
  "Принятие решений без последующей проверки эффектов; пренебрежение регулярными отчетами служб; позднее обнаружение скрытых кризисов.": "Prise de décisions sans suivi d'impact ; négligence des rapports réguliers ; détection tardive des crises latentes.",
  "Принять решения": "Appliquer les décisions",
  "Пробел": "Espace",
  "Проверьте гипотезу.": "Vérifiez l'hypothèse.",
  "Проект оплачивается сразу и один раз": "Projet payé une fois d'avance",
  "Производство": "Production",
  "Процентный долг города ({n0}% в месяц) и кассовый баланс.": "Intérêts de la dette ({n0} % par mois) et trésorerie.",
  "Пять критических переменных: финансы, производство, работа, жилье и благополучие.": "Cinq variables critiques : finances, industrie, travail, logement et bien-être.",
  "Развитие туризма требует синхронного роста гостиниц, рекламы и доступных рабочих рук.": "Le développement du tourisme exige une croissance synchrone des lits, de la publicité et de la main-d'œuvre.",
  "Располагаемый доход": "Revenu disponible",
  "Реактивная ловушка": "Piège réactif",
  "Решения и проекты": "Décisions et projets",
  "СИСТЕМНЫЕ НАБЛЮДЕНИЯ ПО ВАШЕЙ ПАРТИИ": "OBSERVATIONS SYSTÉMIQUES DE VOTRE PARTIE",
  "СНАЧАЛА — ВОПРОСЫ И АНАЛИЗ": "D'ABORD — QUESTIONS ET ANALYSE",
  "СЦЕНАРИЙ: Свободное управление (Песочница)": "SCÉNARIO : Gestion libre (Bac à sable)",
  "Свободно мест: {n0} из {n1}": "Places libres : {n0} sur {n1}",
  "Сводка на главной показывает общее состояние. Подробный отчет раскрывает причины и скрытые механизмы.": "L'aperçu montre la situation globale. Les rapports détaillés révèlent les causes et mécanismes sous-jacents.",
  "Сделайте ход.": "Jouez un tour.",
  "Сейчас налоговая ставка составляет": "Le taux d'imposition actuel est de",
  "Системный радар здоровья города": "Radar systémique de santé urbaine",
  "Системный эталон": "Référence systémique",
  "Скачать подробный аналитический отчет": "Télécharger le rapport analytique détaillé",
  "Следите за балансом между объемом выпуска и внешним спросом на часы.": "Veillez à l'équilibre entre la production de montres et la demande extérieure.",
  "Службы": "Services",
  "Службы реагируют на реальные изменения в городе": "Les services réagissent aux évolutions réelles de la ville",
  "Случалось ли так, что меры по спасению одной сферы неожиданно разрушали баланс в соседней?": "Des mesures de sauvetage dans un domaine ont-elles déstabilisé un secteur voisin ?",
  "Сопоставьте реальный факт с ожиданием. Если что-то пошло не так, исследуйте обратные связи в разделе «Анатомия связей».": "Comparez les faits réels aux attentes. En cas d'écart, étudiez les rétroactions dans « Anatomie des rétroactions ».",
  "Сравнение с модельными профилями поведения": "Comparaison avec les profils comportementaux modèles",
  "Сравнение с эталонами Дёрнера: Индекс благополучия жителей": "Comparaison avec les références de Dörner : Indice de bien-être des habitants",
  "Стандартная": "Standard",
  "Стандартные стартовые условия города Лоххаузен. Горизонт планирования — {n0} лет ({n1} месяцев). Ваша задача — развивать город, соблюдая баланс между экономикой фабрики, благополучием жителей и устойчивостью казны.": "Conditions initiales standard pour Lohhausen. Horizon de {n0} ans ({n1} mois). Développez la ville en équilibrant usine, bien-être et solidité financière.",
  "Станки: {n0}% · Выпуск: {n1} шт.": "Machines : {n0} % · Production : {n1} pcs",
  "Стартовая диспозиция Лоххаузена": "Disposition initiale de Lohhausen",
  "Стратегия:": "Stratégie :",
  "Строительство жилья: {n0} месяцев лага и {n1} новых мест.": "Construction de logements : {n0} mois de délai et {n1} nouvelles places.",
  "Сформулируйте изменение.": "Formulez la modification.",
  "Текущая политика действует каждый месяц. Проекты оплачиваются один раз и дают результат после завершения срока строительства.": "La politique s'applique chaque mois. Les projets sont payés en une fois et portent leurs fruits après livraison.",
  "Траектории Конрада (системный эталон) и Маркуса (реактивная ловушка) построены на основе описаний из глав {n0} и {n1} книги «Логика неудачи» как дидактические ориентиры для самоанализа.": "Les trajectoires de Konrad (référence systémique) et Marcus (piège réactif) sont modélisées d'après les chapitres {n0} et {n1} de « La Logique de l'échec ».",
  "Требование: {n0} · Результат:": "Cible : {n0} · Résultat :",
  "Три вопроса рефлексии Дёрнера": "Trois questions de réflexion de Dörner",
  "Туризм и развитие": "Tourisme et développement",
  "У вас небольшой город, {n0} жителей и десять лет управления ({n1} месяцев). Ваша задача — поддерживать жизнеспособность города и благополучие людей.": "Vous dirigez une petite ville de {n0} habitants sur dix ans de mandat ({n1} mois). Préservez la viabilité et le bien-être.",
  "Узнать ➔ Решить ➔ Подождать ➔ Проверить": "S'informer ➔ Décider ➔ Attendre ➔ Vérifier",
  "Управление": "Gouvernance",
  "Уравнения оригинального компьютерного симулятора {n0}-х годов не опубликованы; мы воссоздали качественную системную динамику, строго следуя описанным в книге закономерностям.": "Les équations du simulateur des années {n0} n'ayant pas été publiées, nous avons recréé une dynamique qualitative fidèle au livre.",
  "Фабрика, жители, казна — части одной связанной системы.": "L'usine, les citoyens et la trésorerie forment un système interconnecté.",
  "Хроника последнего хода": "Chronique du dernier tour",
  "Цель:": "Objectif :",
  "Численные коэффициенты износа оборудования, производительности и спроса.": "Paramètres numériques d'usure des machines, productivité et demande.",
  "Что действительно изменилось в системе?": "Qu'est-ce qui a réellement changé dans le système ?",
  "Что происходит в подразделениях города?": "Que se passe-t-il dans les services municipaux ?",
  "Что смоделировано в этой версии": "Ce qui est modélisé dans cette version",
  "Что сохранено из первоисточника": "Ce qui est préservé de la source originale",
  "Широкие полномочия бургомистра и горизонт {n0} лет ({n1} месяцев).": "Pouvoirs étendus de maire et horizon de {n0} ans ({n1} mois).",
  "Экспортировать снимок партии в JSON": "Exporter la session en JSON",
  "Это разбор событий учебной модели, а не оценка ваших личных способностей. В книге «Логика неудачи» даже опытные политики и ученые совершали похожие системные ошибки. Ценность симулятора — в возможности исследовать последствия без риска для реальных людей.": "Ce bilan analyse un modèle didactique, non vos capacités personnelles. Dans « La Logique de l'échec », des experts ont commis ces mêmes erreurs. L'intérêt réside dans l'apprentissage sans risque.",
  "до нового решения. Налог пополняет казну, но снижает привлекательность города. Обслуживание компенсирует износ оборудования фабрики. Услуги поддерживают медицину и уровень жизни.": "jusqu'à nouvel ordre. L'impôt remplit les caisses mais réduit l'attractivité. L'entretien freine l'usure de l'usine. Les services soutiennent la santé et le niveau de vie.",
  "и требует времени: муниципальное жилье строится {n0} месяцев ({n1} мест), модернизация фабрики длится {n2} месяцев, туристическая инфраструктура строится {n3} месяцев ({n4} мест). За ходом работ можно следить в панели «В работе».": "et exige du temps : logements municipaux {n0} mois ({n1} places), modernisation d'usine {n2} mois, tourisme {n3} mois ({n4} places). Suivi dans l'onglet « En cours ».",
  "⏳ Оборудование фабрики ≥ {n0}%": "⏳ Équipement de l'usine ≥ {n0} %",
  "⏳ Промежуточный срез сценария": "⏳ Bilan d'étape du scénario",
  "⏳ Удовлетворенность жителей ≥ {n0}%": "⏳ Bien-être des habitants ≥ {n0} %",
  "⏳ лаг": "⏳ délai",
  "⚖️ Балансирующий контур (B) · ⏳ Временной лаг (delay)": "⚖️ Boucle équilibrante (B) · ⏳ Retard temporel (délai)",
  "⚠️ Если фабрика не способна выпустить столько часов из-за станков, спрос останется нереализованным.": "⚠️ Si les machines limitent la production de montres, la demande restera insatisfaite.",
  "⚠️ Маркус (Ловушка)": "⚠️ Marcus (Piège)",
  "⚠️ Нет существенных рисков.": "⚠️ Aucun risque majeur.",
  "⚠️ Нет.": "⚠️ Aucun.",
  "⚠️ Низкий риск оттока.": "⚠️ Faible risque d'émigration.",
  "⚠️ Риск деградации социальной среды.": "⚠️ Risque de dégradation du climat social.",
  "⚠️ Траектория Маркуса (Баллистический стиль)": "⚠️ Trajectoire de Marcus (Style balistique)",
  "⚠️ Умеренный риск.": "⚠️ Risque modéré.",
  "⚠️ Эффект проявляется медленно (инерция системы), не ждите мгновенной отдачи через месяц.": "⚠️ L'effet apparaît lentement (inertie du système) ; n'espérez pas de résultat immédiat en un mois.",
  "⚡ Вызов Дёрнера: Преодоление ловушек": "⚡ Le Défi de Dörner : Surmonter les pièges",
  "⚡ Ежемесячные вложения: {n0} тыс. марок.": "⚡ Investissement mensuel : {n0} k Marks.",
  "⚡ Ежемесячные расходы казны: {n0} тыс. марок (потребность города: ~{n1} тыс.).": "⚡ Dépenses mensuelles : {n0} k Marks (besoin municipal : ~{n1} k).",
  "⚡ Около {n0} тыс. м./мес. налоговых поступлений.": "⚡ Environ {n0} k M./mois de recettes fiscales.",
  "⚡ Оптимальный уровень: компенсирует износ оборудования и стабилизирует станки.": "⚡ Niveau optimal : compense l'usure et stabilise les machines.",
  "⚡ Расходы на рекламу туризма: {n0} тыс. м./мес.": "⚡ Dépenses de publicité touristique : {n0} k M./mois.",
  "⚡ Расходы на сбыт: {n0} тыс. м./мес. Расширяет спрос на ~{n1} часов/мес.": "⚡ Dépenses commerciales : {n0} k M./mois. Augmente la demande d'env. {n1} montres/mois.",
  "⚡ Фонд оплаты труда фабрики изменится пропорционально ставке ({n0}%).": "⚡ La masse salariale de l'usine évolue proportionnellement au niveau ({n0} %).",
  "✅ Казна без хронического долга (долг = {n0})": "✅ Trésorerie sans dette chronique (dette = {n0})",
  "❌ Оборудование фабрики ≥ {n0}%": "❌ Équipement de l'usine ≥ {n0} %",
  "❌ Удовлетворенность жителей ≥ {n0}%": "❌ Bien-être des habitants ≥ {n0} %",
  "🌟 Конрад (Эталон)": "🌟 Konrad (Référence)",
  "🌟 Эталон Конрада ({n0}-летнее гармоничное развитие)": "🌟 Référence de Konrad (Développement équilibré sur {n0} ans)",
  "🌲 Туризм и рекреация": "🌲 Tourisme et loisirs",
  "🌲 Экологическая дилемма туризма": "🌲 Dilemme écologique du tourisme",
  "🏛️ Свободное управление (Песочница)": "🏛️ Gestion libre (Bac à sable)",
  "🏛️ Финансы и налоги": "🏛️ Finances et impôts",
  "🏭 Часовая фабрика и производство": "🏭 Fabrique d'horlogerie et production",
  "👥 Общественные услуги и образование": "👥 Services publics et éducation",
  "📖 Глава {n0}, §{n1}: участники часто завышали налоги, не замечая оттока налогоплательщиков.": "📖 Chapitre {n0}, §{n1} : les participants augmentaient souvent les impôts sans remarquer l'exode fiscal.",
  "🔄 Повышает удовлетворенность рабочих фабрики и привлекает кадры.": "🔄 Améliore la satisfaction des ouvriers et attire des compétences.",
  "🔄 Помогает разгружать склады и увеличивает продажи.": "🔄 Aide à écouler les stocks et stimule les ventes.",
  "🔄 Постепенное ухудшение здоровья жителей и отток населения.": "🔄 Dégradation progressive de la santé et émigration de la population.",
  "🔄 Привлекает туристов (текущая вместимость отелей: {n0} мест).": "🔄 Attire des touristes (capacité hôtelière actuelle : {n0} lits).",
  "🔄 Равномерный темп выпуска без простоев.": "🔄 Rythme de production régulier sans temps d'arrêt.",
  "🔄 С задержкой в несколько месяцев повышает квалификацию рабочих и производительность.": "🔄 Augmente avec quelques mois de décalage les compétences et la productivité.",
  "🔄 Умеренное влияние на располагаемый доход.": "🔄 Impact modéré sur le revenu disponible."
};

// Validate that every entry in rawMissing is accounted for
for (const key of rawMissing) {
  if (!en[key]) throw new Error(`Missing EN translation for key: "${key}"`);
  if (!de[key]) throw new Error(`Missing DE translation for key: "${key}"`);
  if (!fr[key]) throw new Error(`Missing FR translation for key: "${key}"`);

  // Validate placeholder matching
  const keyPlaceholders = [...key.matchAll(/\{n\d\}/g)].map(m => m[0]).sort();
  for (const [lang, dict] of [['en', en], ['de', de], ['fr', fr]]) {
    const transPlaceholders = [...dict[key].matchAll(/\{n\d\}/g)].map(m => m[0]).sort();
    if (JSON.stringify(keyPlaceholders) !== JSON.stringify(transPlaceholders)) {
      throw new Error(`Placeholder mismatch for key "${key}" in ${lang}: expected ${JSON.stringify(keyPlaceholders)}, got ${JSON.stringify(transPlaceholders)}`);
    }
  }
}

const fileContent = `// Autogenerated and verified catalog of mayoral cockpit, scenario benchmarks, and systemic dynamics translations.
export default ${JSON.stringify({ en, de, fr }, null, 2)};
`;

fs.writeFileSync('src/locales/cockpit.js', fileContent, 'utf8');
console.log('Successfully generated src/locales/cockpit.js with', rawMissing.length, 'verified entries per language.');
